export const QUERY_KEYS = {
	LOGIN: 'login',
	LOGOUT: 'logout',
	SETTINGS: 'settings',
	UPDATE_PASSWORD: 'updatePassword',
	VALIDATE_EMAIL: 'validateEmail',
	RESET_PASSWORD: 'resetPassword',
	ALL_USERS: 'allUsers',
	ALL_STATS: 'allStats',
	STAT_INSIGHTS: 'statInsights',
	ALL_EMPLOYEES: 'allEmployees',
	DELETE_EMPLOYEE: 'deleteEmployee',
	MY_USERS: 'myUsers',
	ALL_COMPANIES: 'allCompanies',
	MY_COMPANY: 'myCompany',
	ALL_TEMPLATES: 'allTemplates',
	MY_TEMPLATES: 'myTemplates',
	ALL_LOGS: 'allLogs',
	ALL_ERROR_LOGS: 'allErrorLogs',
	ALL_TAGS: 'allTags',
	GET_USER_STATS: 'getUserStats',
	DOWNLOAD_ERROR_LOGS: 'downloadErrorLogs',
	REGISTER_ADMIN: 'registerAdmin',
	REGISTER_EMPLOYEE: 'registerEmployee',
	POPULATE_EMPLOYEE: 'populateEmployee',
	VALIDATE_EMPLOYEE: 'validateEmployee',
	UPDATE_USER: 'updateUser',
	ENABLE_USER: 'enableUser',
	DISABLE_USER: 'disableUser',
	CREATE_COMPANY: 'createCompany',
	UPDATE_COMPANY: 'updateCompany',
	ENABLE_COMPANY: 'enableCompany',
	DISABLE_COMPANY: 'disableCompany',
	CREATE_TEMPLATE: 'createTemplate',
	UPDATE_TEMPLATE: 'updateTemplate',
	ENABLE_TEMPLATE: 'enableTemplate',
	DISABLE_TEMPLATE: 'disableTemplate',
	ALL_GROUPS: 'allGroups',
	CREATE_GROUP: 'createGroup',
	UPDATE_GROUP: 'updateGroup',
	DELETE_GROUP: 'deleteGroup',
	ALL_GROUP_MEMBERS: 'allGroupMembers',
	ADD_GROUP_MEMBERS: 'addGroupMembers',
	REMOVE_GROUP_MEMBERS: 'removeGroupMembers',
	ALL_CAMPAIGNS: 'allCampaigns',
	CAMPAIGN_STATS: 'campaignStats',
	CREATE_CAMPAIGN: 'createCampaign',
	UPDATE_CAMPAIGN: 'updateCampaign',
	DELETE_CAMPAIGN: 'deleteCampaign',
	GET_CAMPAIGN_MEMBERS: 'getCampaignMembers',
	ADD_CAMPAIGN_MEMBERS: 'addCampaignMembers',
	DELETE_CAMPAIGN_MEMBERS: 'deleteCampaignMembers',
	SEND_EMAIL: 'sendEmail',
	TEMPLATE_HELP: 'templateHelp',
	REQUEST_DEMO: 'requestDemo',
	CONTACT_US: 'contactUs'
}

export const JOB_TITLES = [
	'Account Executive',
	'Account Manager',
	'Accounting Clerk',
	'Accounts Payable Specialist',
	'Accounts Receivable Specialist',
	'Administrative Assistant',
	'Assistant Manager',
	'Branch Manager',
	'Brand Manager',
	'Business Analyst',
	'Business Development Manager',
	'Chief Executive Officer (CEO)',
	'Chief Financial Officer (CFO)',
	'Chief Information Officer (CIO)',
	'Chief Information Security Officer (CISO)',
	'Chief Operating Officer (COO)',
	'Client Services Manager',
	'Compliance Manager',
	'Content Manager',
	'Controller',
	'Corporate Trainer',
	'Creative Director',
	'Customer Service Representative',
	'Data Analyst',
	'Data Scientist',
	'Database Administrator',
	'Director of Operations',
	'E-commerce Manager',
	'Engineering Manager',
	'Event Coordinator',
	'Executive Assistant',
	'Facilities Manager',
	'Finance Manager',
	'Financial Analyst',
	'General Manager',
	'Graphic Designer',
	'Human Resources Manager',
	'Human Resources Specialist',
	'IT Support Specialist',
	'IT Manager',
	'Legal Assistant',
	'Logistics Coordinator',
	'Maintenance Technician',
	'Marketing Coordinator',
	'Marketing Manager',
	'Media Planner',
	'Network Administrator',
	'Office Manager',
	'Operations Manager',
	'Payroll Specialist',
	'Product Manager',
	'Project Coordinator',
	'Project Manager',
	'Public Relations Specialist',
	'Purchasing Manager',
	'Quality Assurance Manager',
	'Receptionist',
	'Recruiter',
	'Sales Associate',
	'Sales Manager',
	'Sales Representative',
	'Software Developer',
	'Software Engineer',
	'Store Manager',
	'Supply Chain Manager',
	'Systems Analyst',
	'Technical Support Specialist',
	'Training Specialist',
	'Web Developer',
	'Advertising Manager',
	'Applications Engineer',
	'Art Director',
	'Audit Manager',
	'Benefits Administrator',
	'Branch Supervisor',
	'Budget Analyst',
	'Business Consultant',
	'Business Development Specialist',
	'Business Process Analyst',
	'CAD Designer',
	'Call Center Manager',
	'Campaign Manager',
	'Change Management Specialist',
	'Channel Manager',
	'Claims Adjuster',
	'Client Relationship Manager',
	'Clinical Research Associate',
	'Collections Specialist',
	'Communications Coordinator',
	'Compensation Analyst',
	'Compliance Specialist',
	'Construction Manager',
	'Consultant',
	'Content Strategist',
	'Contract Administrator',
	'Copywriter',
	'Creative Manager',
	'Credit Analyst',
	'Customer Experience Manager',
	'Customer Success Manager',
	'Database Developer',
	'Demand Planner',
	'Desktop Support Technician',
	'Development Manager',
	'Digital Marketing Manager',
	'Director of Finance',
	'Director of Human Resources',
	'Director of Marketing',
	'Director of Sales',
	'Director of Technology',
	'Distribution Manager',
	'E-commerce Specialist',
	'Editor',
	'Electrical Engineer',
	'Environmental Engineer',
	'Event Manager',
	'Executive Director',
	'Facilities Coordinator',
	'Field Service Technician',
	'Financial Controller',
	'Fleet Manager',
	'Graphic Artist',
	'Health and Safety Manager',
	'Help Desk Analyst',
	'HR Coordinator',
	'Industrial Engineer',
	'Information Security Analyst',
	'Inside Sales Representative',
	'Instructional Designer',
	'Insurance Agent',
	'Internal Auditor',
	'Investment Analyst',
	'IT Director',
	'Junior Accountant',
	'Key Account Manager',
	'Laboratory Technician',
	'Landscaping Manager',
	'Legal Counsel',
	'Librarian',
	'Loan Officer',
	'Machine Operator',
	'Maintenance Manager',
	'Market Research Analyst',
	'Medical Billing Specialist',
	'Membership Manager',
	'Mortgage Advisor',
	'Network Engineer',
	'Occupational Health and Safety Specialist',
	'Office Assistant',
	'Operations Coordinator',
	'Organizational Development Specialist',
	'Paralegal',
	'Pharmaceutical Sales Representative',
	'Pharmacy Technician',
	'Physical Therapist',
	'Physician Assistant',
	'Plant Manager',
	'Portfolio Manager',
	'Principal',
	'Product Designer',
	'Production Supervisor',
	'Program Analyst',
	'Program Coordinator',
	'Program Manager',
	'Project Assistant',
	'Property Manager',
	'Public Affairs Specialist',
	'Purchasing Agent',
	'Quality Control Inspector',
	'Real Estate Agent',
	'Regional Manager',
	'Regulatory Affairs Specialist',
	'Research Assistant',
	'Risk Analyst',
	'Safety Coordinator',
	'Sales Consultant',
	'Sales Director',
	'Sales Engineer',
	'Scheduling Coordinator',
	'Security Analyst',
	'Senior Accountant',
	'Senior Business Analyst',
	'Senior Consultant',
	'Senior Data Analyst',
	'Senior Developer',
	'Senior Financial Analyst',
	'Senior Manager',
	'Senior Project Manager',
	'Senior Software Engineer',
	'SEO Specialist',
	'Service Manager',
	'Social Media Manager',
	'Software Architect',
	'Solutions Architect',
	'Supply Chain Analyst',
	'Systems Engineer',
	'Talent Acquisition Specialist',
	'Tax Analyst',
	'Technical Writer',
	'Territory Manager',
	'Training Coordinator',
	'Travel Coordinator',
	'Treasurer',
	'UI/UX Designer',
	'Warehouse Supervisor',
	'Web Designer',
	'Youth Program Coordinator',
	'Chief Marketing Officer (CMO)',
	'Chief Technology Officer (CTO)',
	'Digital Content Manager',
	'Data Engineer',
	'Cybersecurity Analyst',
	'Machine Learning Engineer',
	'Mobile App Developer',
	'DevOps Engineer',
	'IT Security Specialist',
	'Cloud Solutions Architect',
	'Blockchain Developer',
	'Product Owner',
	'Scrum Master',
	'Agile Coach',
	'Full Stack Developer',
	'Front End Developer',
	'Back End Developer',
	'Network Security Engineer',
	'Penetration Tester',
	'Security Consultant',
	'Salesforce Administrator',
	'CRM Manager',
	'Digital Strategist',
	'eCommerce Specialist',
	'User Interface Designer',
	'Interaction Designer',
	'Visual Designer',
	'Business Intelligence Developer',
	'Data Warehouse Architect',
	'Big Data Engineer',
	'Data Visualization Specialist',
	'AI Specialist',
	'Deep Learning Engineer',
	'NLP Specialist',
	'Robotics Engineer',
	'IoT Specialist',
	'AR/VR Developer',
	'Game Developer',
	'Ethical Hacker',
	'Information Assurance Analyst',
	'IT Compliance Analyst',
	'Systems Administrator',
	'Solutions Engineer',
	'Application Support Analyst',
	'Business Systems Analyst',
	'Technical Account Manager',
	'Technical Program Manager',
	'IT Project Manager',
	'IT Business Analyst',
	'IT Infrastructure Manager',
	'ERP Manager',
	'SAP Consultant',
	'Oracle Developer',
	'PeopleSoft Developer',
	'HRIS Analyst',
	'Learning Management System Administrator',
	'Talent Management Specialist',
	'Employee Engagement Specialist',
	'Culture Manager',
	'People Operations Manager',
	'Benefits Specialist',
	'Compensation Manager',
	'HR Generalist',
	'HR Business Partner',
	'Diversity Manager',
	'Inclusion Specialist',
	'Employee Relations Manager',
	'HR Coordinator',
	'HR Consultant',
	'Employee Retention Specialist',
	'Organizational Psychologist',
	'Workforce Planning Specialist',
	'Succession Planning Manager',
	'Chief Happiness Officer',
	'People Development Manager',
	'Internal Communications Specialist',
	'Employee Experience Manager',
	'Engagement Manager',
	'Internal Mobility Specialist',
	'Performance Coach',
	'Executive Coach',
	'Career Development Specialist',
	'Corporate Recruiter',
	'Technical Recruiter',
	'Campus Recruiter',
	'Sourcing Specialist',
	'Talent Scout',
	'Headhunter',
	'Recruitment Coordinator',
	'Recruitment Marketing Specialist',
	'Employment Brand Specialist',
	'Talent Acquisition Partner',
	'Staffing Specialist',
	'Interview Specialist',
	'Background Screening Specialist',
	'Onboarding Specialist',
	'Orientation Specialist',
	'New Hire Coordinator',
	'Apprenticeship Coordinator',
	'Internship Coordinator',
	'Outplacement Specialist',
	'Employment Advisor',
	'Career Transition Specialist',
	'Learning Specialist',
	'Development Specialist',
	'Instructional Coordinator',
	'Training Manager',
	'Corporate Trainer',
	'Leadership Development Specialist',
	'Executive Development Specialist',
	'Coaching Specialist',
	'Mentorship Program Coordinator',
	'Training Coordinator',
	'Learning Management System Specialist',
	'eLearning Developer',
	'Training Content Developer',
	'Employee Trainer',
	'Workplace Trainer',
	'Customer Service Trainer',
	'Sales Trainer',
	'Technical Trainer',
	'Product Trainer',
	'HR Trainer',
	'Skills Development Specialist',
	'Instructional Designer',
	'Training Needs Analyst',
	'Training Delivery Manager',
	'Program Development Manager',
	'Course Developer',
	'Workshop Facilitator',
	'Seminar Coordinator',
	'Training Consultant',
	'Learning Architect',
	'Education Specialist',
	'Curriculum Developer',
	'Training Analyst',
	'Competency Development Specialist',
	'Organizational Learning Consultant',
	'Training Evaluation Specialist',
	'Knowledge Manager',
	'Learning Consultant',
	'Learning Partner',
	'Chief Learning Officer',
	'Training Program Manager',
	'Corporate Learning Consultant',
	'Training Implementation Specialist',
	'Learning and Development Manager',
	'Instructional Technology Specialist',
	'Training Project Manager',
	'Customer Support Specialist',
	'Technical Support Engineer',
	'Marketing Analyst',
	'Product Marketing Manager',
	'Digital Marketing Specialist',
	'Event Planner',
	'Content Writer',
	'Business Development Representative',
	'Client Relationship Specialist',
	'Financial Planner',
	'Investment Banker',
	'Sales Executive',
	'Sales Operations Manager',
	'Inside Sales Manager',
	'Field Sales Representative',
	'Customer Success Specialist',
	'Technical Writer',
	'Creative Copywriter',
	'Marketing Communications Specialist',
	'Public Relations Manager',
	'Media Relations Specialist',
	'Brand Strategist',
	'Product Designer',
	'UX Researcher',
	'Data Architect',
	'Cloud Engineer',
	'Infrastructure Engineer',
	'DevOps Specialist',
	'IT Operations Manager',
	'Network Support Specialist',
	'Cybersecurity Manager',
	'Security Operations Center (SOC) Analyst',
	'Penetration Tester',
	'Vulnerability Analyst',
	'Threat Intelligence Analyst',
	'Forensic Analyst',
	'Incident Response Specialist',
	'Risk Management Specialist',
	'IT Compliance Manager',
	'Information Assurance Manager',
	'Security Auditor',
	'Privacy Officer',
	'Chief Data Officer (CDO)',
	'Data Governance Manager',
	'Data Quality Manager',
	'Data Steward',
	'Business Intelligence Analyst',
	'BI Developer',
	'Analytics Manager',
	'Marketing Data Analyst',
	'Sales Analyst',
	'HR Data Analyst',
	'Financial Data Analyst',
	'Operations Analyst',
	'Supply Chain Analyst',
	'Inventory Analyst',
	'Logistics Manager',
	'Transportation Manager',
	'Fleet Coordinator',
	'Warehouse Manager',
	'Inventory Control Specialist',
	'Shipping and Receiving Manager',
	'Import/Export Coordinator',
	'Customs Compliance Specialist',
	'Procurement Specialist',
	'Vendor Relations Manager',
	'Supplier Quality Engineer',
	'Contract Negotiator',
	'Purchasing Coordinator',
	'Strategic Sourcing Manager',
	'Category Manager',
	'Commodity Manager',
	'Materials Manager',
	'Production Planner',
	'Manufacturing Engineer',
	'Production Engineer',
	'Quality Engineer',
	'Process Engineer',
	'Industrial Engineering Technician',
	'Plant Supervisor',
	'Operations Supervisor',
	'Maintenance Supervisor',
	'Facilities Supervisor',
	'Safety Manager',
	'Environmental Manager',
	'Sustainability Manager',
	'Energy Manager',
	'Lean Manufacturing Specialist',
	'Six Sigma Black Belt',
	'Continuous Improvement Manager',
	'Production Control Manager',
	'Assembly Line Supervisor',
	'CNC Programmer',
	'Machinist',
	'Tool and Die Maker',
	'Maintenance Technician',
	'Industrial Electrician',
	'Mechanical Engineer',
	'Electrical Technician',
	'Instrumentation Technician',
	'Controls Engineer',
	'Automation Engineer',
	'Robotics Technician',
	'Mechatronics Engineer',
	'Calibration Technician',
	'Research Scientist',
	'Laboratory Manager',
	'Clinical Lab Technician',
	'Biomedical Engineer',
	'Chemical Engineer',
	'Process Development Scientist',
	'Formulation Scientist',
	'Pharmaceutical Scientist',
	'Regulatory Affairs Manager',
	'Quality Control Analyst',
	'Microbiologist',
	'Biochemist',
	'Biostatistician',
	'Epidemiologist',
	'Clinical Research Coordinator',
	'Clinical Data Manager',
	'Medical Science Liaison',
	'Medical Writer',
	'Regulatory Document Specialist',
	'Clinical Operations Manager',
	'Pharmacovigilance Specialist',
	'Drug Safety Associate',
	'Pharmaceutical Sales Representative',
	'Medical Device Sales Representative',
	'Healthcare Account Manager',
	'Medical Billing and Coding Specialist',
	'Patient Services Coordinator',
	'Health Information Technician',
	'Medical Records Manager',
	'Health Services Manager',
	'Healthcare Consultant',
	'Nursing Home Administrator',
	'Clinical Nurse Manager',
	'Director of Nursing',
	'Registered Nurse (RN)',
	'Licensed Practical Nurse (LPN)',
	'Certified Nursing Assistant (CNA)',
	'Nurse Practitioner',
	'Physician Assistant',
	'Physical Therapist Assistant',
	'Occupational Therapist Assistant',
	'Speech-Language Pathologist',
	'Respiratory Therapist',
	'Radiologic Technologist',
	'Diagnostic Medical Sonographer',
	'MRI Technologist',
	'CT Technologist',
	'Nuclear Medicine Technologist',
	'Medical Laboratory Technician',
	'Histotechnologist',
	'Phlebotomist',
	'Cardiovascular Technologist',
	'Surgical Technologist',
	'Sterile Processing Technician',
	'Anesthesia Technician',
	'Dental Hygienist',
	'Dental Assistant',
	'Orthodontic Assistant',
	'Veterinary Technician',
	'Veterinary Assistant',
	'Veterinary Practice Manager',
	'Veterinary Sales Representative',
	'Animal Care Technician',
	'Zookeeper',
	'Wildlife Biologist',
	'Conservation Scientist',
	'Environmental Scientist',
	'Ecologist',
	'Soil and Plant Scientist',
	'Water Resource Specialist',
	'Geospatial Analyst',
	'GIS Technician',
	'Urban Planner',
	'Regional Planner',
	'Transportation Planner',
	'City Manager',
	'Municipal Clerk',
	'Public Works Director',
	'Building Inspector',
	'Code Enforcement Officer',
	'Fire Inspector',
	'Emergency Management Director',
	'Homeland Security Specialist',
	'Border Patrol Agent',
	'Criminal Investigator',
	'Intelligence Analyst',
	'Counterterrorism Analyst',
	'Cyber Intelligence Analyst',
	'Operations Research Analyst',
	'Defense Analyst',
	'Military Logistics Specialist',
	'Aerospace Engineer',
	'Aeronautical Engineer',
	'Astronautical Engineer',
	'Spacecraft Systems Engineer',
	'Avionics Technician',
	'Air Traffic Controller',
	'Airport Operations Manager',
	'Pilot',
	'Flight Engineer',
	'Flight Attendant',
	'Aircraft Mechanic',
	'Aircraft Maintenance Engineer',
	'Airline Customer Service Agent',
	'Airline Reservation Agent',
	'Baggage Handler',
	'Ramp Agent',
	'Ground Support Equipment Technician',
	'Transportation Security Officer',
	'Logistics Analyst',
	'Supply Chain Planner',
	'Distribution Center Manager',
	'Fulfillment Center Supervisor',
	'E-commerce Logistics Coordinator',
	'Freight Broker',
	'Freight Forwarder',
	'Customs Broker',
	'Export Compliance Specialist',
	'Import Specialist',
	'Trade Compliance Manager',
	'International Trade Specialist',
	'Global Supply Chain Manager',
	'Supply Chain Risk Manager',
	'Sustainability Analyst',
	'Environmental Compliance Specialist',
	'Renewable Energy Specialist',
	'Energy Efficiency Consultant',
	'Green Building Consultant',
	'LEED Accredited Professional',
	'Sustainability Coordinator',
	'Corporate Social Responsibility (CSR) Manager',
	'Environmental Health and Safety (EHS) Manager',
	'Waste Management Specialist',
	'Recycling Coordinator',
	'Environmental Policy Analyst',
	'Environmental Program Manager',
	'Climate Change Analyst',
	'Carbon Management Specialist',
	'Renewable Energy Project Manager',
	'Energy Auditor',
	'Solar Energy Engineer',
	'Wind Energy Engineer',
	'Geothermal Engineer',
	'Hydroelectric Engineer',
	'Energy Storage Engineer',
	'Battery Engineer',
	'Electric Vehicle Engineer',
	'Sustainable Transportation Planner',
	'Urban Sustainability Planner',
	'Sustainable Agriculture Specialist',
	'Organic Farm Manager',
	'Community Garden Coordinator',
	'Agroforestry Specialist',
	'Agricultural Extension Agent',
	'Food Systems Coordinator',
	'Food Safety Specialist',
	'Public Health Nutritionist',
	'Dietitian',
	'Nutritionist',
	'Wellness Coordinator',
	'Health Coach',
	'Fitness Trainer',
	'Personal Trainer',
	'Group Fitness Instructor',
	'Yoga Instructor',
	'Pilates Instructor',
	'Strength and Conditioning Coach',
	'Exercise Physiologist',
	'Kinesiologist',
	'Sports Nutritionist',
	'Athletic Trainer',
	'Sports Coach',
	'Sports Psychologist',
	'Sports Statistician',
	'Sports Marketing Manager',
	'Sports Event Coordinator',
	'Sports Agent',
	'Scout',
	'Team Manager',
	'Club Manager',
	'Athlete',
	'Professional Player',
	'Amateur Athlete',
	'Sports Official',
	'Umpire',
	'Referee',
	'Game Day Coordinator',
	'Stadium Operations Manager',
	'Ticket Sales Manager',
	'Merchandise Manager',
	'Brand Ambassador',
	'Public Relations Coordinator',
	'Social Media Coordinator',
	'Communications Specialist',
	'Community Relations Manager',
	'Event Manager',
	'Event Coordinator',
	'Meeting Planner',
	'Convention Services Manager',
	'Trade Show Coordinator',
	'Exhibit Designer',
	'Set Designer',
	'Lighting Technician',
	'Sound Technician',
	'Stage Manager',
	'Production Assistant',
	'Art Director',
	'Creative Director',
	'Graphic Designer',
	'Illustrator',
	'Animator',
	'Motion Graphics Designer',
	'Video Editor',
	'Videographer',
	'Photographer',
	'Photo Editor',
	'Stylist',
	'Fashion Designer',
	'Costume Designer',
	'Textile Designer',
	'Interior Designer',
	'Architect',
	'Landscape Architect',
	'Urban Designer',
	'Industrial Designer',
	'Product Designer',
	'Package Designer',
	'Exhibit Designer',
	'Furniture Designer',
	'Toy Designer',
	'Game Designer',
	'Character Designer',
	'Storyboard Artist',
	'Agronomist',
	'Allergy Specialist',
	'Animal Control Officer',
	'Appliance Repair Technician',
	'Archivist',
	'Artificial Intelligence Specialist',
	'Audio-Visual Technician',
	'Auto Parts Manager',

	'Bailiff',
	'Baker',
	'Bank Examiner',
	'Bioinformatics Scientist',
	'Building Maintenance Worker',
	'Business Intelligence Analyst',
	'Career Counselor',
	'Carpet Installer',
	'Casino Dealer',
	'Catering Coordinator',
	'Ceramics Artist',
	'Chauffeur',
	'Childcare Worker',
	'Clinical Laboratory Technician',
	'Clinical Social Worker',
	'Commercial Diver',
	'Commercial Loan Officer',
	'Communications Specialist',
	'Compensation and Benefits Manager',
	'Computer Systems Analyst',
	'Construction Foreman',
	'Contract Manager',
	'Costume Designer',
	'Court Reporter',
	'Credit Analyst',
	'Crime Analyst',
	'Cytotechnologist',
	'Data Analytics Manager',
	'Data Entry Specialist',
	'Demographer',
	'Dental Hygienist',
	'Dental Technician',
	'Director of Operations',
	'Distribution Manager',
	'Document Control Specialist',
	'Drywall Installer',
	'Education Administrator',
	'Electrical Inspector',
	'Electro-Mechanical Technician',
	'Emergency Management Specialist',
	'Employment Specialist',
	'Endodontist',
	'Energy Auditor',
	'Environmental Health Specialist',
	'Environmental Scientist',
	'Equal Opportunity Officer',
	'Event Designer',
	'Exhibit Preparator',
	'Fashion Stylist',
	'Field Service Engineer',
	'Film Editor',
	'Financial Aid Counselor',
	'Fish and Game Warden',
	'Flight Engineer',
	'Floriculturist',
	'Foreclosure Specialist',
	'Fraud Investigator',
	'Fundraising Coordinator',
	'Genealogist',
	'Geneticist',
	'Geographic Information Systems Technician',
	'Glazier',
	'Government Program Analyst',
	'Grant Writer',
	'Greenhouse Manager',
	'Health and Safety Engineer',
	'Hearing Aid Specialist',
	'High School Counselor',
	'Histotechnician',
	'Home Health Aide',
	'Hospice Coordinator',
	'Hotel Desk Clerk',
	'Housekeeping Manager',
	'Human Resources Administrator',
	'HVAC Installer',
	'Hydroelectric Plant Technician',
	'Import/Export Manager',
	'Industrial Machinery Mechanic',
	'Industrial Safety Manager',
	'Information Technology Analyst',
	'Insurance Claims Adjuster',
	'Interior Decorator',
	'International Relations Specialist',
	'Investment Underwriter',
	'Jewelry Appraiser',
	'Judicial Assistant',
	'Juvenile Probation Officer',
	'Kennel Manager',
	'Laboratory Technician',
	'Landscape Contractor',
	'Legislative Analyst',
	'Licensing Coordinator',
	'Life Coach',
	'Lifeguard',
	'Logistics Coordinator',
	'Loss Prevention Manager',
	'Machining Supervisor',
	'Makeup Artist',
	'Management Consultant',
	'Market Research Analyst',
	'Marriage and Family Therapist',
	'Massage Therapist',
	'Materials Engineer',
	'Media Relations Manager',
	'Medical Equipment Preparer',
	'Medical Laboratory Technician',
	'Mental Health Technician',
	'Museum Curator',
	'Music Therapist',
	'Network Architect',
	'Nonprofit Program Manager',
	'Nuclear Medicine Technologist',
	'Occupational Health Specialist',
	'Office Clerk',
	'Oncology Nurse',
	'Operations Research Analyst',
	'Parole Officer',
	'Patent Examiner',
	'Payroll Manager',
	'Personal Care Aide',
	'Pest Control Technician',
	'Petroleum Engineer',
	'Phlebotomist',
	'Photojournalist',
	'Physical Education Teacher',
	'Pipeline Engineer',
	'Political Scientist',
	'Printmaking Artist',
	'Process Improvement Manager',
	'Production Planner',
	'Project Scheduler',
	'Prosthetist',
	'Psychometrician',
	'Public Health Administrator',
	'Public Relations Coordinator',
	'Purchasing Coordinator',
	'Quality Assurance Inspector',
	'Quality Control Manager',
	'Radiation Therapist',
	'Radiologic Technician',
	'Real Estate Broker',
	'Records Manager',
	'Recycling Coordinator',
	'Rehabilitation Counselor',
	'Remote Sensing Technician',
	'Renewable Energy Technician',
	'Research Coordinator',
	'Respiratory Care Practitioner',
	'Robotics Technician',
	'Safety Coordinator',
	'School Administrator',
	'School Nurse',
	'Script Editor',
	'Search Engine Optimization Specialist',
	'Security Manager',
	'Self-Enrichment Education Teacher',
	'Semiconductor Processor',
	'Social Media Strategist',
	'Software Quality Assurance Engineer',
	'Solar Photovoltaic Installer',
	'Speech Pathologist',
	'Sports Agent',
	'Sports Marketing Coordinator',
	'Statistician',
	'Stockbroker',
	'Strategic Planner',
	'Supply Chain Planner',
	'Surveyor',
	'Sustainability Manager',
	'Tax Preparer',
	'Technical Illustrator',
	'Telecommunications Equipment Installer',
	'Textile Designer',
	'Theater Director',
	'Title Examiner',
	'Tour Guide',
	'Toxicologist',
	'Training and Development Manager',
	'Transit Police Officer',
	'Transportation Planner',
	'Travel Agent',
	'Ultrasound Technician',
	'Urban Planner',
	'Usability Analyst',
	'User Experience (UX) Researcher',
	'Utility Meter Reader',
	'Veterinarian',
	'Veterinary Assistant',
	'Video Game Tester',
	'Virologist',
	'Vocational Counselor',
	'Water Treatment Specialist',
	'Agile Product Owner',
	'AI Ethics Specialist',
	'Algorithm Developer',
	'Amazon Web Services (AWS) Specialist',
	'Application Security Engineer',
	'Artificial Intelligence (AI) Consultant',
	'Autonomous Vehicle Technician',
	'Biometrician',
	'Blockchain Analyst',
	'Brand Protection Manager',
	'Business Continuity Manager',
	'Business Process Engineer',
	'Chatbot Developer',
	'Chief Sustainability Officer',
	'Cloud Infrastructure Engineer',
	'Cloud Security Engineer',
	'Compliance Data Analyst',
	'Content Strategist',
	'COVID-19 Contact Tracer',
	'Cryptocurrency Analyst',
	'Customer Journey Specialist',
	'Cyber Forensics Analyst',
	'Data Compliance Officer',
	'Data Privacy Officer',
	'DevOps Consultant',
	'Digital Transformation Manager',
	'Disaster Recovery Manager',
	'Diversity and Inclusion Specialist',
	'Drone Operator',
	'eCommerce Marketing Manager',
	'Environmental Data Analyst',
	'Ethical Hacker',
	'FinTech Analyst',
	'Gene Therapy Specialist',
	'Genetic Counselor',
	'Geospatial Data Scientist',
	'Green Building Engineer',
	'Green Energy Consultant',
	'Head of Remote Work',
	'Health Informatics Specialist',
	'Human-Machine Teaming Manager',
	'Hydrogen Energy Specialist',
	'Immersive Experience Designer',
	'Industrial Data Scientist',
	'Influencer Marketing Manager',
	'Innovation Strategist',
	'IoT Architect',
	'IT Process Improvement Manager',
	'IT Service Delivery Manager',
	'Kubernetes Engineer',
	'Labor Market Analyst',
	'Machine Learning Operations (MLOps) Engineer',
	'Market Intelligence Analyst',
	'MedTech Product Manager',
	'Microbiome Scientist',
	'Mobility Solutions Architect',
	'Nanotechnology Engineer',
	'Natural Language Processing (NLP) Engineer',
	'Neural Network Specialist',
	'Offsite Construction Manager',
	'Online Community Manager',
	'Open Source Intelligence (OSINT) Analyst',
	'Operations Research Scientist',
	'Pandemic Response Coordinator',
	'Patient Experience Manager',
	'Plant-Based Food Scientist',
	'Precision Agriculture Specialist',
	'Privacy Engineer',
	'Public Health Data Scientist',
	'Quantum Computing Developer',
	'Recycling Program Manager',
	'Regenerative Medicine Specialist',
	'Renewable Energy Analyst',
	'Retail Data Analyst',
	'Risk Management Consultant',
	'Robotics Process Automation (RPA) Developer',
	'Safety Data Analyst',
	'Satellite Data Analyst',
	'Scrum Master',
	'Search Engine Marketing (SEM) Specialist',
	'Security Operations Manager',
	'Service Design Lead',
	'Smart Building Technician',
	'Social Media Content Moderator',
	'Software-as-a-Service (SaaS) Developer',
	'Solar Energy Consultant',
	'Sustainability Data Analyst',
	'Sustainable Supply Chain Manager',
	'Telehealth Coordinator',
	'Telemedicine Specialist',
	'Threat Intelligence Analyst',
	'Transportation Systems Analyst',
	'Trust and Safety Officer',
	'Urban Farming Specialist',
	'User Onboarding Specialist',
	'Virtual Reality (VR) Developer',
	'Visual Data Analyst',
	'Waste Reduction Manager',
	'Water Resources Engineer',
	'Wind Turbine Technician',
	'5G Network Engineer',
	'Agile Coach',
	'Alternative Energy Consultant',
	'Autonomous Systems Engineer',
	'Behavioral Data Analyst',
	'Blockchain Developer',
	'Brand Experience Manager',
	'Chief Happiness Officer',
	'Cloud Solutions Engineer',
	'Corporate Responsibility Manager',
	'Customer Data Analyst',
	'Cyber Security Manager',
	'Data Ethicist',
	'Digital Product Manager',
	'Drone Pilot',
	'E-commerce Specialist',
	'Environmental Engineer',
	'ESG (Environmental, Social, and Governance) Analyst',
	'Experience Designer',
	'FinTech Developer',
	'Genetic Data Analyst',
	'Green Energy Project Manager',
	'Head of AI',
	'Health Data Analyst',
	'Human Factors Engineer',
	'Industrial Automation Engineer',
	'Information Governance Manager',
	'IT Asset Manager',
	'IT Governance Manager',
	'Life Coach',
	'Machine Learning Scientist',
	'Mobile Marketing Manager',
	'Natural Resource Specialist',
	'Neurofeedback Specialist',
	'Online Reputation Manager',
	'Patient Advocate',
	'Performance Marketing Manager',
	'Precision Medicine Specialist',
	'Privacy Consultant',
	'Product Data Analyst',
	'Product Security Engineer',
	'Quantum Information Scientist',
	'Remote Project Manager',
	'Renewable Energy Project Developer',
	'Robotics Software Engineer',
	'Safety Program Manager',
	'Security Compliance Manager',
	'Smart Grid Engineer',
	'Social Media Strategist',
	'Software Implementation Specialist',
	'Solar Installation Technician',
	'Sustainability Coordinator',
	'Sustainable Product Manager',
	'Systems Integration Engineer',
	'Technical Evangelist',
	'Telecommuting Specialist',
	'Urban Mobility Planner',
	'User Engagement Manager',
	'Virtual Event Planner',
	'Visual Effects (VFX) Artist',
	'Waste Management Consultant',
	'Water Conservation Specialist',
	'Wind Energy Engineer',
	'Zero Waste Program Manager',
	'AI Policy Specialist',
	'Augmented Reality (AR) Developer',
	'Biodefense Researcher',
	'Biostatistician',
	'Carbon Credit Analyst',
	'Climate Change Analyst',
	'Clinical Data Manager',
	'Corporate Wellness Coordinator',
	'Crowdfunding Specialist',
	'Cyber Defense Analyst',
	'Data Integration Specialist',
	'Digital Analytics Manager',
	'Digital Business Analyst',
	'Disaster Recovery Analyst',
	'Energy Efficiency Engineer',
	'Environmental Consultant',
	'Epidemiologist',
	'Food Safety Inspector',
	'Green Construction Manager',
	'Head of Digital',
	'Health and Safety Advisor',
	'Hydrogen Fuel Cell Engineer',
	'Industrial Safety Engineer',
	'Innovation Manager',
	'Internet of Things (IoT) Developer',
	'IT Disaster Recovery Manager',
	'Knowledge Engineer',
	'Lead Generation Specialist',
	'Market Research Consultant',
	'Medical Device Sales Representative',
	'Microgrid Engineer',
	'Mobile Application Developer',
	'Natural Resources Manager',
	'Organizational Development Consultant',
	'Plant Manager',
	'Sustainability Consultant'
]

export const LOCATIONS = [
	'Hamburg, Germany',
	'Waterford, Ireland',
	'Eastbourne, United Kingdom',
	'Edinburgh, United Kingdom',
	'Basingstoke, United Kingdom',
	'Innsbruck, Austria',
	'Porto Alegre, Brazil',
	'Laval, Canada',
	'Columbia, United States',
	'Kyoto, Japan',
	'Sydney, Australia',
	'Nonthaburi, Thailand',
	'New Haven, United States',
	'Pittsburgh, United States',
	'Bangor, United States',
	'Sakai, Japan',
	'Taichung, Taiwan',
	'Gold Coast, Australia',
	'Monterrey, Mexico',
	'Chennai, India',
	'Nagpur, India',
	'Cape Town, South Africa',
	'Fortaleza, Brazil',
	'Mesquite, United States',
	'Jackson, United States',
	'Riverside, United States',
	'Saint Paul, United States',
	'Chula Vista, United States',
	'Elizabeth, United States',
	'George Town, Malaysia',
	'Dijon, France',
	'Lancaster, United States',
	'Torrance, United States',
	'Lima, Peru',
	'Pretoria, South Africa',
	'Surabaya, Indonesia',
	'Whitehaven, United Kingdom',
	'Davao City, Philippines',
	'Toledo, United States',
	'Brest, France',
	'Cuenca, Ecuador',
	'Hollywood, United States',
	'Recife, Brazil',
	'Bridlington, United Kingdom',
	'Philadelphia, United States',
	'Munich, Germany',
	'Montpellier, France',
	'Indianapolis, United States',
	'Winchester, United Kingdom',
	'Liège, Belgium',
	'Caloocan, Philippines',
	'Virginia Beach, United States',
	'Tianjin, China',
	'Lincoln, United States',
	'Kampala, Uganda',
	'Paterson, United States',
	'Hemel Hempstead, United Kingdom',
	'Wigan, United Kingdom',
	'Pomona, United States',
	'Geneva, Switzerland',
	'Nice, France',
	'Cheyenne, United States',
	'Shah Alam, Malaysia',
	'Essen, Germany',
	'Anchorage, United States',
	'Sendai, Japan',
	'Hai Phong, Vietnam',
	'Cardiff, United Kingdom',
	'Escondido, United States',
	'Daejeon, South Korea',
	'Bekasi, Indonesia',
	'Portland, United States',
	'Baton Rouge, United States',
	'Brownsville, United States',
	'Lincoln, United Kingdom',
	'Naperville, United States',
	'Caracas, Venezuela',
	'Garland, United States',
	'Cochabamba, Bolivia',
	'La Serena, Chile',
	'Bandung, Indonesia',
	'Port St. Lucie, United States',
	'Kansas City, United States',
	'Gillingham, United Kingdom',
	'Ulsan, South Korea',
	'Edmonton, Canada',
	'Springfield, United States',
	'Auckland, New Zealand',
	'Tijuana, Mexico',
	'Agra, India',
	'Montevideo, Uruguay',
	'Hanoi, Vietnam',
	'Tainan, Taiwan',
	'Boston, United States',
	'Fontana, United States',
	'Ibadan, Nigeria',
	'Tokyo, Japan',
	'Can Tho, Vietnam',
	'Round Rock, United States',
	'Sunnyvale, United States',
	'Vancouver, United States',
	'Maidstone, United Kingdom',
	'Mar del Plata, Argentina',
	'Kent, United States',
	'Halifax, United Kingdom',
	'Cleveland, United States',
	'Cologne, Germany',
	'Harrogate, United Kingdom',
	'Tynemouth, United Kingdom',
	'High Wycombe, United Kingdom',
	'Arequipa, Peru',
	'Albuquerque, United States',
	'Hiroshima, Japan',
	'Fort Lauderdale, United States',
	'Florence, Italy',
	'Orange, United States',
	'Bangalore, India',
	'Kendal, United Kingdom',
	'Mombasa, Kenya',
	'Taunton, United Kingdom',
	'Croydon, United Kingdom',
	'Stockton-on-Tees, United Kingdom',
	'Bologna, Italy',
	'Warren, United States',
	'Los Angeles, United States',
	'Kettering, United Kingdom',
	'Cheltenham, United Kingdom',
	'Rennes, France',
	'Clermont-Ferrand, France',
	'Slough, United Kingdom',
	'Jaipur, India',
	'Sacramento, United States',
	'Salinas, United States',
	'Cary, United States',
	'Windsor, Canada',
	'Perth, Australia',
	'London, Canada',
	'Ho Chi Minh City, Vietnam',
	'Newport News, United States',
	'Bristol, United Kingdom',
	'Green Bay, United States',
	'Tallahassee, United States',
	'Johor Bahru, Malaysia',
	'Greenville, United States',
	'Roseville, United States',
	'Surprise, United States',
	'Santa Fe, Argentina',
	'Toulouse, France',
	'Catania, Italy',
	'Ahmedabad, India',
	'Christchurch, New Zealand',
	'Montgomery, United States',
	'Grand Prairie, United States',
	'Blackpool, United Kingdom',
	'Seville, Spain',
	'Salvador, Brazil',
	'Phoenix, United States',
	'Medellín, Colombia',
	'Topeka, United States',
	'Basel, Switzerland',
	'Chengdu, China',
	'Galway, Ireland',
	'San Diego, United States',
	'Puebla, Mexico',
	'Lansing, United States',
	'Eindhoven, Netherlands',
	'Kanpur, India',
	'Spalding, United Kingdom',
	'Seattle, United States',
	'Corpus Christi, United States',
	'Manchester, United States',
	'Milan, Italy',
	'Louisville, United States',
	'Columbus, United States',
	'Boston, United Kingdom',
	'Tampa, United States',
	'Bilbao, Spain',
	'Le Mans, France',
	'Reading, United Kingdom',
	'Aylesbury, United Kingdom',
	'Oceanside, United States',
	'Austin, United States',
	'Aurora, United States',
	'Honolulu, United States',
	'Monroe, United States',
	'Grimsby, United Kingdom',
	'Zamboanga City, Philippines',
	'Barquisimeto, Venezuela',
	'Lucknow, India',
	'Rockford, United States',
	'Anaheim, United States',
	'Chester, United Kingdom',
	'Modesto, United States',
	'Guildford, United Kingdom',
	'Bern, Switzerland',
	'Lynchburg, United States',
	'Chandler, United States',
	'Guadalajara, Mexico',
	'Barcelona, Spain',
	'Medan, Indonesia',
	'Inverness, United Kingdom',
	'Pembroke Pines, United States',
	'Hanover, Germany',
	'Fresno, United States',
	'Ayr, United Kingdom',
	'Vienna, Austria',
	'Mobile, United States',
	'Nanjing, China',
	'Yokohama, Japan',
	'Jakarta, Indonesia',
	'Wolverhampton, United Kingdom',
	'Santiago, Chile',
	'Juneau, United States',
	'Iquitos, Peru',
	'Yakima, United States',
	'Bracknell, United Kingdom',
	'St. Paul, United States',
	'Bedford, United Kingdom',
	'Birmingham, United Kingdom',
	'St. George, United States',
	'Stevenage, United Kingdom',
	'Montreal, Canada',
	'Amiens, France',
	'North Las Vegas, United States',
	'Akron, United States',
	'Las Vegas, United States',
	'Worcester, United States',
	'Saint-Étienne, France',
	'Gulfport, United States',
	'Liverpool, United Kingdom',
	'Olathe, United States',
	'Ontario, United States',
	'Newcastle, Australia',
	'Torreón, Mexico',
	'Grantham, United Kingdom',
	'Irving, United States',
	'Wakefield, United Kingdom',
	'Hayward, United States',
	'Melbourne, Australia',
	'Kolkata, India',
	'Richmond, United States',
	'Santa Clarita, United States',
	'Dundee, United Kingdom',
	'Gwangju, South Korea',
	'Chiang Mai, Thailand',
	'Hartlepool, United Kingdom',
	'Visalia, United States',
	'Durban, South Africa',
	'Seoul, South Korea',
	'Peterborough, United Kingdom',
	'Barranquilla, Colombia',
	'Fort Myers, United States',
	'Plano, United States',
	'Zurich, Switzerland',
	'San Francisco, United States',
	'Morgantown, United States',
	'Dresden, Germany',
	'Lyon, France',
	'Winston–Salem, United States',
	'Reims, France',
	'New York, United States',
	'South Shields, United Kingdom',
	'Patna, India',
	'Markham, Canada',
	'Madison, United States',
	'Ipoh, Malaysia',
	'Darlington, United Kingdom',
	'La Plata, Argentina',
	'Savannah, United States',
	'Wuhan, China',
	'Visakhapatnam, India',
	'Mekelle, Ethiopia',
	'Ciudad del Este, Paraguay',
	'Kingston upon Hull, United Kingdom',
	'Sioux Falls, United States',
	'Wallasey, United Kingdom',
	'Wellington, New Zealand',
	'Bellevue, United States',
	'Barrow-in-Furness, United Kingdom',
	'Taipei, Taiwan',
	'Chiclayo, Peru',
	'Loughborough, United Kingdom',
	'Pasadena, United States',
	'Flint, United States',
	'Adelaide, Australia',
	'Bolton, United Kingdom',
	'Boise, United States',
	'Carlisle, United Kingdom',
	'São Paulo, Brazil',
	'Rio de Janeiro, Brazil',
	'Belo Horizonte, Brazil',
	'Durham, United Kingdom',
	'Toulon, France',
	'Fort Wayne, United States',
	'Seongnam, South Korea',
	'Santa Ana, United States',
	'Runcorn, United Kingdom',
	'Frederick, United States',
	'Kennewick, United States',
	'Sheffield, United Kingdom',
	'Falkirk, United Kingdom',
	'New Taipei, Taiwan',
	'Farnborough, United Kingdom',
	'Limoges, France',
	'Lakewood, United States',
	'Portsmouth, United Kingdom',
	'Busan, South Korea',
	'Bangor, United Kingdom',
	'Omaha, United States',
	'Moreno Valley, United States',
	'Stuttgart, Germany',
	'Livingston, United Kingdom',
	'Beijing, China',
	'Perpignan, France',
	'Oldham, United Kingdom',
	'Gateshead, United Kingdom',
	'Winnipeg, Canada',
	'Chiba, Japan',
	'Davenport, United States',
	'Braga, Portugal',
	'Charleroi, Belgium',
	'Bremen, Germany',
	'Valencia, Venezuela',
	'Sarasota, United States',
	'Bhopal, India',
	'Chattanooga, United States',
	'Workington, United Kingdom',
	'Guayaquil, Ecuador',
	'Brighton, United Kingdom',
	'Pensacola, United States',
	'Oxnard, United States',
	'Hattiesburg, United States',
	'Poole, United Kingdom',
	'Medford, United States',
	'Manchester, United Kingdom',
	'Memphis, United States',
	'Rugby, United Kingdom',
	'Cape Coral, United States',
	'Nakhon Ratchasima, Thailand',
	'Billings, United States',
	'Bury, United Kingdom',
	'Antwerp, Belgium',
	'The Hague, Netherlands',
	'Bordeaux, France',
	'Clarksville, United States',
	'Milton Keynes, United Kingdom',
	'Luton, United Kingdom',
	'Suwon, South Korea',
	'Overland Park, United States',
	'Marseille, France',
	'Tempe, United States',
	'Halifax, Canada',
	'Weston-super-Mare, United Kingdom',
	'Concepción, Chile',
	'Henderson, United States',
	'College Station, United States',
	'Kigali, Rwanda',
	'Venice, Italy',
	'Angers, France',
	'Calgary, Canada',
	'Jacksonville, United States',
	'Fremont, United States',
	'Epsom, United Kingdom',
	'Hamilton, Canada',
	'Tours, France',
	'Cartagena, Colombia',
	'Dunedin, New Zealand',
	'Roanoke, United States',
	'Saitama, Japan',
	'Bari, Italy',
	'Nairobi, Kenya',
	'Chongqing, China',
	'Le Havre, France',
	'Oran, Algeria',
	'Long Beach, United States',
	'Raleigh, United States',
	'Wichita, United States',
	'Ocala, United States',
	'Encarnación, Paraguay',
	'Vaughan, Canada',
	'York, United Kingdom',
	'Quito, Ecuador',
	'Palma, Spain',
	'Cork, Ireland',
	'Thousand Oaks, United States',
	'Daegu, South Korea',
	'Incheon, South Korea',
	'Newcastle-under-Lyme, United Kingdom',
	'Newark, United States',
	'Swansea, United Kingdom',
	'Dayton, United States',
	'Hong Kong, China',
	'Fukuoka, Japan',
	'Gilbert, United States',
	'Nashville, United States',
	'Salford, United Kingdom',
	'Skegness, United Kingdom',
	'Spokane, United States',
	'Rotherham, United Kingdom',
	'Linz, Austria',
	'Hamamatsu, Japan',
	'Buffalo, United States',
	'Colorado Springs, United States',
	'Santa Rosa, United States',
	'McKinney, United States',
	'Querétaro, Mexico',
	'Mendoza, Argentina',
	'Addis Ababa, Ethiopia',
	'Dortmund, Germany',
	'Syracuse, United States',
	'Kaohsiung, Taiwan',
	'Delhi, India',
	'Stoke-on-Trent, United Kingdom',
	'Grenoble, France',
	'Huntsville, United States',
	'Baltimore, United States',
	'Asheville, United States',
	'Paris, France',
	'Glasgow, United Kingdom',
	'St. Louis, United States',
	'Cambridge, United Kingdom',
	'San Bernardino, United States',
	'Niigata, Japan',
	'Harlow, United Kingdom',
	'Cali, Colombia',
	'Ogden, United States',
	'Amarillo, United States',
	'Düsseldorf, Germany',
	'Mumbai, India',
	'San Jose, United States',
	'Ludhiana, India',
	'Sterling Heights, United States',
	'Dodoma, Tanzania',
	'Hyderabad, India',
	'Nashua, United States',
	'Zaragoza, Spain',
	'Ipswich, United Kingdom',
	'Clearwater, United States',
	'Nottingham, United Kingdom',
	'Exeter, United Kingdom',
	'Metz, France',
	'Provo, United States',
	'Murcia, Spain',
	'Surat, India',
	'Milwaukee, United States',
	'Colchester, United Kingdom',
	'Duluth, United States',
	'Cedar Rapids, United States',
	'Salt Lake City, United States',
	'Southend-on-Sea, United Kingdom',
	'Abuja, Nigeria',
	'Gloucester, United Kingdom',
	'Swindon, United Kingdom',
	'Gonder, Ethiopia',
	'Crawley, United Kingdom',
	'Ottawa, Canada',
	'Bakersfield, United States',
	'Ghent, Belgium',
	'Vila Nova de Gaia, Portugal',
	'Trujillo, Peru',
	'Valparaíso, Chile',
	'Curitiba, Brazil',
	'Shizuoka, Japan',
	'Winston-Salem, United States',
	'Fort Collins, United States',
	'Vancouver, Canada',
	'Wilmington, United States',
	'Punta del Este, Uruguay',
	'Guangzhou, China',
	'La Paz, Bolivia',
	'Houston, United States',
	'Miami, United States',
	'Sunderland, United Kingdom',
	'Charleston, United States',
	'Dublin, Ireland',
	'Rome, Italy',
	'Kisumu, Kenya',
	'Hastings, United Kingdom',
	'Johannesburg, South Africa',
	'Rotterdam, Netherlands',
	'Mulhouse, France',
	'Atlanta, United States',
	'Minneapolis, United States',
	'Lisbon, Portugal',
	'Graz, Austria',
	'Algiers, Algeria',
	'Sapporo, Japan',
	'Tulsa, United States',
	'Dar es Salaam, Tanzania',
	'San Miguel de Tucumán, Argentina',
	'Shreveport, United States',
	'Warrington, United Kingdom',
	'Utrecht, Netherlands',
	'Birmingham, United States',
	'Santa Cruz, Bolivia',
	'Kitchener, Canada',
	'Coventry, United Kingdom',
	'Toronto, Canada',
	'McAllen, United States',
	'Oxford, United Kingdom',
	'Evansville, United States',
	'Surrey, Canada',
	'Lubbock, United States',
	'Scottsdale, United States',
	'Glendale, United States',
	'Leicester, United Kingdom',
	'Genoa, Italy',
	'Worthing, United Kingdom',
	'Hilo, United States',
	'San Antonio, United States',
	'Augusta, United States',
	'Brisbane, Australia',
	'Maidenhead, United Kingdom',
	'Newcastle, United Kingdom',
	'Providence, United States',
	'Stockton, United States',
	'Frankfurt, Germany',
	'Quezon City, Philippines',
	'Da Nang, Vietnam',
	'Lagos, Nigeria',
	'Rochester, United States',
	'Yonkers, United States',
	'Santa Fe, United States',
	'Ciudad Juárez, Mexico',
	'Fayetteville, United States',
	'Port Harcourt, Nigeria',
	'West Valley City, United States',
	'Laredo, United States',
	'Thornton, United States',
	'Kuala Lumpur, Malaysia',
	'Woking, United Kingdom',
	'Orlando, United States',
	'Dewsbury, United Kingdom',
	'Rosario, Argentina',
	'Wrexham, United Kingdom',
	'Little Rock, United States',
	'Southampton, United Kingdom',
	'Bradford, United Kingdom',
	'Orléans, France',
	'Hialeah, United States',
	'Victoria, Canada',
	'Gainesville, United States',
	'London, United Kingdom',
	'Elk Grove, United States',
	'Irvine, United States',
	'Corona, United States',
	'Greeley, United States',
	'Amadora, Portugal',
	'Turin, Italy',
	'Manila, Philippines',
	'Macclesfield, United Kingdom',
	'Doncaster, United Kingdom',
	'Macon, United States',
	'Belfast, United Kingdom',
	'Huntington Beach, United States',
	'Mexico City, Mexico',
	'Chelmsford, United Kingdom',
	'Keighley, United Kingdom',
	'Salzburg, Austria',
	'Hampton, United States',
	'Aberdeen, United Kingdom',
	'Norfolk, United States',
	'Bridgeport, United States',
	'Osaka, Japan',
	'Preston, United Kingdom',
	'Barnsley, United Kingdom',
	'Daytona Beach, United States',
	'Bend, United States',
	'Fullerton, United States',
	'Lausanne, Switzerland',
	'Naples, Italy',
	'Des Moines, United States',
	'Salta, Argentina',
	'Charlotte, United States',
	'Eugene, United States',
	'Reno, United States',
	'Birkenhead, United Kingdom',
	'Kano, Nigeria',
	'Derby, United Kingdom',
	'Greensboro, United States',
	'Hamilton, New Zealand',
	'Basildon, United Kingdom',
	'Pune, India',
	'Chesapeake, United States',
	'Chicago, United States',
	'Leipzig, Germany',
	'Madrid, Spain',
	'Kalamazoo, United States',
	'Mérida, Mexico',
	'Salisbury, United Kingdom',
	'Hartford, United States',
	'Middlesbrough, United Kingdom',
	'Córdoba, Argentina',
	'Maracaibo, Venezuela',
	'Oklahoma City, United States',
	'Shanghai, China',
	'Canberra, Australia',
	'Limerick, Ireland',
	'Rancho Cucamonga, United States',
	'Allentown, United States',
	'Watford, United Kingdom',
	'Shenzhen, China',
	'Mississauga, Canada',
	'Washington D.C., United States',
	'Nagoya, Japan',
	'Kawasaki, Japan',
	'Manaus, Brazil',
	'Cincinnati, United States',
	'Palermo, Italy',
	'Antofagasta, Chile',
	'Hat Yai, Thailand',
	'Lille, France',
	'Crewe, United Kingdom',
	'Frisco, United States',
	'León, Mexico',
	'Ann Arbor, United States',
	'Waco, United States',
	'New Orleans, United States',
	'Tacoma, United States',
	'Garden Grove, United States',
	'Valencia, Spain',
	'Boulder, United States',
	'Brussels, Belgium',
	'Bath, United Kingdom',
	'Palmdale, United States',
	'Oakland, United States',
	'Scunthorpe, United Kingdom',
	'Lafayette, United States',
	'Newport, United Kingdom',
	'Detroit, United States',
	'Dallas, United States',
	'Quebec City, Canada',
	'Durham, United States',
	'Hangzhou, China',
	'Telford, United Kingdom',
	'Alexandria, United States',
	'St. Petersburg, United States',
	'Plymouth, United Kingdom',
	'Strasbourg, France',
	'Santa Barbara, United States',
	'Porto, Portugal',
	'Las Cruces, United States',
	'Amsterdam, Netherlands',
	'Kitakyushu, Japan',
	'Miramar, United States',
	'Nuremberg, Germany',
	'Mansfield, United Kingdom',
	'Grand Rapids, United States',
	'Bangkok, Thailand',
	'Salem, United States',
	'Knoxville, United States',
	'Brasília, Brazil',
	'Rochdale, United Kingdom',
	'Las Palmas, Spain',
	'Arlington, United States',
	'Málaga, Spain',
	'Peoria, United States',
	'Buenos Aires, Argentina',
	'Fargo, United States',
	'Berlin, Germany',
	'Erie, United States',
	'Denver, United States',
	'Norwich, United Kingdom',
	'Bogotá, Colombia',
	'Goyang, South Korea',
	'Joliet, United States',
	'Stirling, United Kingdom',
	'Killeen, United States',
	'Scarborough, United Kingdom',
	'Cebu City, Philippines',
	"Xi'an, China",
	'Tucson, United States',
	'El Paso, United States',
	'Nantes, France',
	'Leeds, United Kingdom',
	'Asunción, Paraguay',
	'Lexington, United States',
	'Huddersfield, United Kingdom',
	'Brampton, Canada',
	'Kobe, Japan',
	'Bellingham, United States',
	'Fort Worth, United States',
	'Jersey City, United States'
]

export const DEPARTMENTS = [
	'Human Resources (HR)',
	'Finance',
	'Accounting',
	'Marketing',
	'Sales',
	'Customer Service',
	'Cyber Security',
	'Information Technology (IT)',
	'Research and Development (R&D)',
	'Operations',
	'Legal',
	'Procurement',
	'Supply Chain Management',
	'Logistics',
	'Public Relations (PR)',
	'Corporate Communications',
	'Business Development',
	'Strategy',
	'Risk Management',
	'Compliance',
	'Quality Assurance (QA)',
	'Environmental Health and Safety (EHS)',
	'Facilities Management',
	'Maintenance',
	'Administration',
	'Training and Development',
	'Internal Audit',
	'Investor Relations',
	'Product Management',
	'Project Management',
	'Engineering',
	'Design',
	'Data Analytics',
	'Business Intelligence',
	'Corporate Social Responsibility (CSR)',
	'Event Management',
	'Knowledge Management',
	'Media Relations',
	'Government Relations',
	'Export/Import',
	'Innovation',
	'Corporate Security',
	'Records Management',
	'Talent Acquisition',
	'Compensation and Benefits',
	'Employee Relations',
	'Organizational Development',
	'Service Management',
	'Vendor Management',
	'Customer Experience',
	'Digital Transformation',
	'Change Management',
	'Content Management',
	'Field Operations',
	'Global Operations',
	'Health and Wellness',
	'Industrial Relations',
	'Learning and Development',
	'Management Information Systems (MIS)',
	'Network Operations',
	'Performance Management',
	'Procurement and Sourcing',
	'Production',
	'Property Management',
	'Regulatory Affairs',
	'Resource Planning',
	'Retail Operations',
	'Sales Operations',
	'Security Operations',
	'Service Delivery',
	'Social Media Management',
	'Technical Support',
	'Technology Management',
	'Trade Compliance',
	'User Experience (UX)',
	'Visual Merchandising',
	'Warehouse Management',
	'Workforce Management',
	'Customer Insights',
	'Diversity and Inclusion',
	'Ethics and Compliance',
	'Franchise Management',
	'Investor Services',
	'Lean Management',
	'Market Research',
	'Merchandising',
	'Organizational Effectiveness',
	'Outreach',
	'Partner Management',
	'Performance Improvement',
	'Product Development',
	'Program Management',
	'Public Affairs',
	'Records and Information Management',
	'Retail Development',
	'Revenue Management',
	'Sales Enablement',
	'Sustainability',
	'Technical Services',
	'Telecommunications',
	'Training',
	'Trust and Safety',
	'Workplace Experience'
]

export const LANGUAGES = [
	'Afrikaans',
	'Albanian',
	'Amharic',
	'Arabic',
	'Armenian',
	'Assamese',
	'Azerbaijani',
	'Basque',
	'Belarusian',
	'Bengali',
	'Bosnian',
	'Bulgarian',
	'Burmese',
	'Catalan',
	'Cebuano',
	'Chichewa',
	'Chinese (Cantonese)',
	'Chinese (Mandarin)',
	'Corsican',
	'Croatian',
	'Czech',
	'Danish',
	'Dutch',
	'English',
	'English (US)',
	'Esperanto',
	'Estonian',
	'Filipino',
	'Finnish',
	'French',
	'Galician',
	'Georgian',
	'German',
	'Greek',
	'Gujarati',
	'Haitian Creole',
	'Hausa',
	'Hawaiian',
	'Hebrew',
	'Hindi',
	'Hmong',
	'Hungarian',
	'Icelandic',
	'Igbo',
	'Indonesian',
	'Irish',
	'Italian',
	'Japanese',
	'Javanese',
	'Kannada',
	'Kazakh',
	'Khmer',
	'Kinyarwanda',
	'Korean',
	'Kurdish (Kurmanji)',
	'Kurdish (Sorani)',
	'Kyrgyz',
	'Lao',
	'Latin',
	'Latvian',
	'Lithuanian',
	'Luxembourgish',
	'Macedonian',
	'Malagasy',
	'Malay',
	'Malayalam',
	'Maltese',
	'Maori',
	'Marathi',
	'Mongolian',
	'Nepali',
	'Norwegian',
	'Pashto',
	'Persian',
	'Polish',
	'Portuguese',
	'Punjabi',
	'Romanian',
	'Russian',
	'Samoan',
	'Scots Gaelic',
	'Serbian',
	'Sesotho',
	'Shona',
	'Sindhi',
	'Sinhala',
	'Slovak',
	'Slovenian',
	'Somali',
	'Spanish',
	'Sundanese',
	'Swahili',
	'Swedish',
	'Tagalog',
	'Tajik',
	'Tamil',
	'Tatar',
	'Telugu',
	'Thai',
	'Turkish',
	'Turkmen',
	'Ukrainian',
	'Urdu',
	'Uyghur',
	'Uzbek',
	'Vietnamese',
	'Welsh',
	'Xhosa',
	'Yiddish',
	'Yoruba',
	'Zulu'
]
